[workspace]
members = [
    "fuzzysearch-common",
    "fuzzysearch-api",
    "fuzzysearch-file-index",
    "fuzzysearch-dump",
    "fuzzysearch-web"
]

resolver = "2"

[workspace.metadata.release]
sign-tag = true
