[workspace]
members = [
    "fuzzysearch-common",
    "fuzzysearch-api",
    "fuzzysearch-file-index",
    "fuzzysearch-dump",
    "fuzzysearch-web",
    "fuzzysearch-loader",
]

[workspace.metadata.release]
sign-tag = true
