[package]
name = "fuzzysearch-api"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Syfaro <syfaro@huefox.com>"]

[dependencies]
axum = { version = "0.5.15", features = ["multipart", "macros"] }
bkapi-client = { git = "https://github.com/Syfaro/bkapi.git" }
bytes = "1.2.1"
chrono = { version = "0.4.22", features = ["serde"] }
clap = { version = "3.2.20", features = ["derive", "env"] }
dotenv = "0.15.0"
eyre = "0.6.8"
hex = "0.4.3"
image = "0.23.14"
img_hash = "3.2.0"
pomsky-macro = "0.6.0"
regex = "1.6.0"
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
sqlx = { version = "0.6.1", features = ["postgres", "offline", "runtime-tokio-rustls", "chrono", "json"] }
tokio = { version = "1.20.1", features = ["macros"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["cors", "trace", "auth"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
utoipa = { version = "2", features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { version = "2", features = ["axum"] }
url = "2.2.2"

fuzzysearch-common = { path = "../fuzzysearch-common", features = ["api-types"] }
