name: Checks

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: sudo apt-get install protobuf-compiler libavutil-dev
      - uses: Swatinem/rust-cache@v2
      - name: Lint
        run: |
          echo "FUZZYSEARCH_API_TOKEN=$FUZZYSEARCH_API_TOKEN" > .env
          cargo fmt -- --check
          cargo clippy -- -D warnings
        env:
          FUZZYSEARCH_API_TOKEN: ${{ secrets.FUZZYSEARCH_API_TOKEN }}
      - name: Test
        run: |
          echo "FUZZYSEARCH_API_TOKEN=$FUZZYSEARCH_API_TOKEN" > .env
          cargo test --all-features
        env:
          FUZZYSEARCH_API_TOKEN: ${{ secrets.FUZZYSEARCH_API_TOKEN }}
