name: Images

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get install protobuf-compiler
      - name: Extract tag data
        run: |
          export CRATE_NAME=$(echo $GITHUB_REF_NAME | sed 's/-v.*//')
          echo "CRATE_NAME=$CRATE_NAME" >> $GITHUB_ENV
          export CRATE_VERSION=$(echo $GITHUB_REF_NAME | sed 's/.*-v/v/')
          echo "CRATE_VERSION=$CRATE_VERSION" >> $GITHUB_ENV
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ env.CRATE_NAME }}
      - name: Build JavaScript for API
        if: ${{ env.CRATE_NAME == 'fuzzysearch-api' }}
        run: |
          cd fuzzysearch-api
          yarn install --check-files
          NODE_ENV=production yarn run build
      - name: Build binary
        run: |
          cargo build --release --bin ${{ env.CRATE_NAME }}
          mv target/release/${{ env.CRATE_NAME }} ${{ env.CRATE_NAME }}/${{ env.CRATE_NAME }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/syfaro/fuzzysearch-next/${{ env.CRATE_NAME }}
          tags: |
            type=raw,value=${{ env.CRATE_VERSION }}
            type=raw,value=latest
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ env.CRATE_NAME }}/Dockerfile
